source "https://rubygems.org"

ruby "3.2.0"
gem "sinatra", "~>1.4.7"
gem "sinatra-contrib"
gem "erubis"
gem "puma", "~>4.3.12"
gem "rack-test"
gem "minitest"
gem "minitest-reporters"
gem "redcarpet"
gem "bcrypt"
